### ISSUE TITLE
Multiple Uploads

### ISSUE THREAD

**Issue by HeroHann** [termoose/skyput#1]
As far as I see only one upload at a time is supported. Would be nice to upload all files in a given folder separately...

**Comment by termoose** [comment]
It's now supported with the `-all` flag!

**Comment by HeroHann** [comment]
When I cd into a folder and then put skyput -all I get:

flag provided but not defined: -all
Usage of skyput:
  -ddg
    	make file searchable on dappdappgo
  -list
    	list previous uploads
  -portal
    	select portal


But no upload...

**Comment by termoose** [comment]
If you installed using brew you would have to upgrade using `brew install termoose/tap/skyput`

**Comment by HeroHann** [comment]
Well I thought I had updated but had made an error...thx!
